# server
FROM node:18-alpine
WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm ci --only=production

# only need sse-server.js and its deps
COPY sse-server.js ./

EXPOSE 4000
CMD ["node", "sse-server.js"]
