# worker
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package manifests
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci --only=production

# Copy subscriber code
COPY worker.js ./

# Default command
CMD ["node", "worker.js"]

